class Sample():
    
    recruitment_incomplete = [
    "Có việc nào đang tuyển không?",
    "Bạn có thể gợi ý việc làm phù hợp cho mình không?",
    "Có việc làm mới nào không?",
    "Có công ty nào đang cần tuyển dụng không?",
    "Bạn có danh sách việc làm hot hiện nay không?",
    "Có việc nào lương cao không?",
    "Mình muốn tìm một công việc, bạn có gợi ý không?",
    "Có việc nào dễ xin không?",
    "Bạn có thể giúp mình tìm việc không?",
    "Có công việc nào dành cho người mới ra trường không?",
    "Bạn có biết chỗ nào đang tuyển gấp không?",
    "Có việc nào làm từ xa không?",
    "Có công việc part-time nào không?",
    "Có chỗ nào đang tuyển nhân viên không?",
    "Bạn có thể giới thiệu vài công việc mới không?",
    "Có việc nào làm tại nhà không?",
    "Có ngành nào đang thiếu nhân sự không?",
    "Có việc nào không yêu cầu kinh nghiệm không?",
    "Bạn có thể tìm việc giúp mình không?",
    "Có công ty lớn nào đang tuyển nhiều không?",
    "Có cơ hội nào phù hợp với mình không?",
    "Có việc nào đang mở ứng tuyển không?",
    "Bạn có danh sách việc làm mới nhất không?",
    "Có việc nào thời gian linh hoạt không?",
    "Có công việc nào chỉ cần làm cuối tuần không?",
    "Có việc nào hiện đang cần người gấp không?",
    "Có vị trí nào dễ trúng tuyển không?",
    "Có việc nào dành cho sinh viên không?",
    "Bạn có thể gợi ý vài lựa chọn việc làm không?",
    "Có việc nào nhàn mà lương ổn không?",
    "Có công việc nào đang hot trên thị trường không?",
    "Có chỗ nào đang mở nhiều vị trí không?",
    "Có việc nào không cần bằng cấp không?",
    "Có công ty nào đang tuyển nhiều nhất bây giờ không?",
    "Có việc nào cho người chưa có kinh nghiệm không?",
    "Có việc nào làm online ổn định không?",
    "Bạn có thể giới thiệu công việc phù hợp với hồ sơ của mình không?",
    "Có việc nào chỉ cần phỏng vấn đơn giản không?",
    "Có chỗ nào đang tuyển số lượng lớn không?",
    "Có việc nào có thể bắt đầu ngay không?",
    "Có công việc nào giúp mình kiếm thêm thu nhập không?",
    "Có cơ hội việc làm nào mà bạn thấy hợp với mình không?",
    "Có việc nào không yêu cầu ngoại ngữ không?",
    "Có việc nào tuyển quanh năm không?",
    "Có công việc nào thử việc nhanh không?",
    "Có việc nào ít áp lực không?",
    "Có công ty nào thường xuyên tuyển mới không?",
    "Có việc nào dễ xin trong thời điểm này không?",
    "Có công việc nào ít yêu cầu kỹ năng không?",
    "Có việc nào linh hoạt về thời gian làm việc không?",
    "Có cơ hội nào cho người muốn đổi ngành không?",
    "Có việc nào đang cần tuyển gấp trong tuần này không?",
    "Có công việc nào không giới hạn độ tuổi không?",

]

    recruitment_complete = [
    "Tôi muốn tìm việc lập trình viên Python tại Hà Nội lương khoảng 20 triệu.",
    "Có công việc Data Analyst nào ở TP.HCM không yêu cầu nhiều kinh nghiệm không?",
    "Cho tôi danh sách các công việc marketing part-time tại Đà Nẵng.",
    "Có vị trí lập trình Java nào làm remote với mức lương trên 25 triệu không?",
    "Tôi muốn tìm việc kế toán full-time ở quận 1 TP.HCM.",
    "Có công ty nào đang tuyển nhân viên bán hàng ca tối tại Hà Nội không?",
    "Cho tôi xem việc làm thiết kế đồ họa ở TP.HCM dành cho sinh viên mới ra trường.",
    "Có việc QA tester nào tại Hà Nội yêu cầu 1 năm kinh nghiệm không?",
    "Tôi muốn ứng tuyển vị trí Product Manager tại công ty ABC ở TP.HCM.",
    "Có công việc chăm sóc khách hàng online cho người biết tiếng Anh không?",
    "Cho tôi danh sách các công ty đang tuyển Developer blockchain ở Đà Nẵng lương trên 30 triệu.",
    "Có việc dạy tiếng Anh bán thời gian tại Hải Phòng không?",
    "Mình muốn tìm việc làm phục vụ nhà hàng tại Hà Nội ca chiều.",
    "Có công ty nào ở TP.HCM đang tuyển fresher ReactJS không?",
    "Tôi cần việc nhân viên giao hàng xe máy tại khu vực Cầu Giấy Hà Nội.",
    "Có việc lập trình Unity 3D nào cho sinh viên mới tốt nghiệp tại TP.HCM không?",
    "Cho tôi danh sách công việc bán hàng online tại Hà Nội có bảo hiểm xã hội.",
    "Tôi muốn tìm vị trí Data Engineer ở TP.HCM yêu cầu 2 năm kinh nghiệm.",
    "Có công việc thiết kế UI/UX nào remote nhưng vẫn trả lương theo giờ không?",
    "Cho tôi thông tin tuyển dụng vị trí Digital Marketing Leader tại công ty XYZ ở Đà Nẵng.",
    "Tôi muốn tìm việc lập trình C++ tại Hà Nội cho người có 3 năm kinh nghiệm.",
    "Có việc làm JavaScript Developer nào tại TP.HCM mức lương 15–20 triệu không?",
    "Cho tôi danh sách các vị trí nhân viên kinh doanh ở Bình Dương full-time.",
    "Có công ty nào đang tuyển nhân sự nhân sự HR Manager tại Đà Nẵng không?",
    "Tôi muốn tìm việc kế toán trưởng ở Hà Nội yêu cầu ít nhất 5 năm kinh nghiệm.",
    "Có việc Customer Support nào tại TP.HCM ca đêm không?",
    "Cho tôi thông tin tuyển dụng vị trí PHP Developer ở Cần Thơ lương trên 18 triệu.",
    "Mình muốn tìm việc thực tập sinh marketing tại Hà Nội.",
    "Có công ty nào đang tuyển Backend Developer NodeJS tại Đà Nẵng không?",
    "Cho tôi danh sách việc làm Graphic Designer tại Hải Phòng full-time.",
    "Có việc QA automation nào tại TP.HCM cho người biết Selenium không?",
    "Tôi muốn ứng tuyển vị trí Product Owner tại công ty Fintech ở Hà Nội.",
    "Có công việc Data Scientist nào tại TP.HCM cho người có 1 năm kinh nghiệm không?",
    "Cho tôi danh sách công việc Tester tại Đà Nẵng có hỗ trợ đào tạo.",
    "Có vị trí lập trình Golang nào làm remote lương 2000 USD trở lên không?",
    "Tôi cần việc nhân viên phục vụ tại quán cà phê ở quận 3 TP.HCM.",
    "Có công ty nào đang tuyển nhân viên telesales ở Hà Nội ca sáng không?",
    "Cho tôi việc làm Java Backend Developer tại Đà Nẵng yêu cầu 2 năm kinh nghiệm.",
    "Có việc kế toán bán thời gian tại Hải Dương không?",
    "Tôi muốn tìm việc Content Creator ở TP.HCM có thể làm việc từ xa.",
    "Có công việc lập trình PHP nào tại Hà Nội lương 25 triệu không?",
    "Cho tôi thông tin các vị trí Data Engineer tại Đà Nẵng yêu cầu tiếng Anh.",
    "Có công ty nào ở Hà Nội đang tuyển nhân viên bảo trì hệ thống IT không?",
    "Tôi muốn tìm việc Digital Marketing ở TP.HCM cho người mới tốt nghiệp.",
    "Có việc nhân viên nhập liệu online nào được trả lương theo giờ không?",
    "Cho tôi danh sách công việc quản lý cửa hàng tại Hải Phòng.",
    "Có vị trí UI Designer nào ở Hà Nội full-time không?",
    "Tôi cần tìm việc làm tài xế xe tải tại TP.HCM ca ngày.",
    "Có công việc chăm sóc thú cưng tại Đà Nẵng không?",
    "Cho tôi danh sách các công ty đang tuyển Blockchain Developer ở Hà Nội lương từ 40 triệu.",
    "Có việc lập trình React Native nào cho người có 1 năm kinh nghiệm ở TP.HCM không?",
    "Tôi muốn tìm việc nhân viên hỗ trợ khách hàng tiếng Nhật tại Đà Nẵng."
]



    chitchatSample = [ "Thời tiết hôm nay như thế nào?", 
                  "Ngoài trời nóng bao nhiêu?", 
                  "Ngày mai có mưa không?",
                  "Nhiệt độ hiện tại là bao nhiêu?",
                  "Bạn có thể cho tôi biết điều kiện thời tiết hiện tại không?",
                  "Cuối tuần này có nắng không?", 
                  "Nhiệt độ hôm qua là bao nhiêu?", 
                  "Đêm nay trời sẽ lạnh đến mức nào?", 
                  "Ai là tổng thống đầu tiên của Hoa Kỳ?",
                  "Chiến tranh thế giới thứ hai kết thúc vào năm nào?", 
                  "Bạn có thể kể cho tôi về lịch sử của internet không?", 
                  "Tháp Eiffel được xây dựng vào năm nào?",
                  "Ai đã phát minh ra điện thoại?", 
                  "Tên của bạn là gì?", "Bạn có tên không?", 
                  "Tôi nên gọi bạn là gì?", 
                  "Ai đã tạo ra bạn?", 
                  "Bạn bao nhiêu tuổi?", 
                  "Bạn có thể kể cho tôi một sự thật thú vị không?",
                  "Bạn có biết bất kỳ câu đố thú vị nào không?", 
                  "Màu sắc yêu thích của bạn là gì?", 
                  "Bộ phim yêu thích của bạn là gì?", 
                  "Bạn có sở thích nào không?", 
                  "Ý nghĩa của cuộc sống là gì?", 
                  "Bạn có thể kể cho tôi một câu chuyện cười không?",
                  "Thủ đô của Pháp là gì?", 
                  "Dân số thế giới là bao nhiêu?", 
                  "Có bao nhiêu châu lục?",
                  "Ai đã viết 'Giết con chim nhại'?",
                  "Bạn có thể cho tôi một câu nói của Albert Einstein không?" ]
    
    @classmethod
    def  as_dict(cls):
        return {
            "recruitment_incomplete": cls.recruitment_incomplete,
            "recruitment_complete": cls.recruitment_complete,
            "chitchatSample": cls.chitchatSample
        }
        
    
    

